### ISSUE TITLE
Cannot read property 'length' of null on Ionic 3.7.1

### ISSUE THREAD

**Issue by icharge** [zyra/ionic-super-tabs#193] opened 2017-10-19 10:28 UTC
Still worked, But error show up on startup.

![image](https://user-images.githubusercontent.com/1619007/31766579-2a5c6164-b4f2-11e7-80e6-5226eb62eb1d.png)

@angular version 4.4.3
@ionic-angular 3.7.1
ionic2-super-tabs 4.1.3

```
> ionic info                                              
                                                          
cli packages: (D:\path\to\project\node_modules)
                                                          
    @ionic/cli-utils  : 1.13.1                            
    ionic (Ionic CLI) : 3.13.2                            
                                                          
global packages:                                          
                                                          
    cordova (Cordova CLI) : 7.1.0                         
                                                          
local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.1

System:                                                   

    Android SDK Tools : 25.2.5                            
    Node              : v6.11.3                           
    npm               : 3.10.10                           
    OS                : Windows 10                        

Misc:                                                     

    backend : legacy
```

I didn't try on Production build yet.

**Comment by icsvortex666** [comment] 2017-10-26 14:22
@ihadeed can you take a look at this issue?

**Comment by icsvortex666** [comment] 2017-11-06 15:15
@ihadeed can you please take a look, it's super annoying.
Thank you.

**Comment by icsvortex666** [comment] 2017-11-08 20:49
Has anyone got a fix for this?? @ihadeed

**Comment by icharge** [comment] 2017-11-09 02:22
This guy is busy for now?

**Comment by ihadeed** [comment] 2017-11-10 22:17
Sorry for the delay.

What versions are you guys using?

I just tested with latest Ionic version & Ionic super tabs and it seem to be working fine.

**Comment by icsvortex666** [comment] 2017-11-11 02:51
@ihadeed It's been happening in all versions starting with 3.7.1.
I'm upgrading to 3.9.2 will report back if it happens again.

**Comment by icsvortex666** [comment] 2017-11-11 03:10
@ihadeed yup, issue still there. Also tabs not working correctly.
<img width="427" alt="screen shot 2017-11-11 at 12 09 37 am" src="https://user-images.githubusercontent.com/4429087/32685669-a084e6de-c674-11e7-810f-95e57fd85e8f.png">

<img width="474" alt="screen shot 2017-11-11 at 12 09 02 am" src="https://user-images.githubusercontent.com/4429087/32685661-95c54a54-c674-11e7-921f-866a51fcd89a.png">
<img width="410" alt="screen shot 2017-11-11 at 12 08 40 am" src="https://user-images.githubusercontent.com/4429087/32685662-95f6d02e-c674-11e7-8d32-23c9e25d46fc.png">
<img width="860" alt="screen shot 2017-11-11 at 12 08 22 am" src="https://user-images.githubusercontent.com/4429087/32685665-9618c238-c674-11e7-91f6-855db408bbc7.png">
<img width="837" alt="screen shot 2017-11-11 at 12 07 33 am" src="https://user-images.githubusercontent.com/4429087/32685666-963ad6c0-c674-11e7-9e35-3b8106d92c06.png">

**Comment by ihadeed** [comment] 2017-11-11 22:49
Thanks, I'll try to reproduce this issue.

I wasn't getting it when running the example project.

**Comment by lincolnthree** [comment] 2017-12-10 16:28
Also getting this same issue with 4.1.5. Works after downgrading to 4.1.4:

```
localhost:marit-mtg-ionic lb3$ ionic info

cli packages: (/Users/lb3/projects/maritlabs/marit-mtg-ionic/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.8 
    Node       : v9.0.0
    npm        : 2.15.12 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy
```

**Comment by ihadeed** [comment] 2018-01-26 07:07
Unable to reproduce.. maybe the issue is gone with the latest versions

**Comment by lincolnthree** [comment] 2018-01-26 15:41
Try setting the page as the initial NavRoot, then using a deeplink to access a different page:

NavRoot initial: "PageWithSuperTabs" --> app.component.ts: this.nav.setRoot(PageWithSuperTabs);

Deeplink Page: "PageWithoutSuperTabs" --> localhost:8100/#nosupertabs

I was able to prevent these errors in development by setting a different root page (one without SuperTabs), but if I use the page *with* super tabs, it comes back.

**Comment by ihadeed** [comment] 2018-01-26 21:50
Thanks for the info @lincolnthree .. I'll try what you mentioned.

**Comment by pipoa** [comment] 2019-01-18 18:14
I have the same problem whenever rapidly switch from one page to another , or refresh itself (setRootPage). it seems a view Page is leaving before SuperTab "tabs" are created, it crashed. 
I resolve the problem by delay show super-tabs on the page.
```
in .ts file
ionViewDidLoad() {
       // delay
        setTimeout(() => {
            this.showSuperTab = true;
        }, 100);
}

in .html file
    <super-tabs *ngIf="showSuperTab" .... >
      <super-tab [root]="page1" [rootParams]="navParams" ></super-tab>
      <super-tab [root]="page2" [rootParams]="navParams"></super-tab>
      .....
    </super-tabs>

```

However, this is not the perfect solution, we should deal w/ the bug inside super-tabs.js when array of _views is zero.
```
in super-tabs.js file 
    SuperTabs.prototype.fireLifecycleEvent = function (events) {
        var activeView = this.getActiveTab().getActive();    //  <-- inside getActive(),  this._views: Array(0) causes exception
        events.forEach(function (event) {
        ....
```

**Closed** 2019-03-28 22:40 UTC
Labels: bug, wontfix
